# Introducing NumPy
---

* NumPy ("Numeric Python") supports:

  * Multidimensional arrays (`ndarray`)
  * Matrices and linear algebra operations
  * Random number generation
  * Fourier transforms
  * Polynomials
  
* NumPy provides fast precompiled functions for numerical routines


* https://www.numpy.org/


## NumPy Arrays

* Standard Python Library provides lists and 1d arrays (array.array)

  * Lists are general containers for objects
  * Arrays are 1d containers for objects of the same type
  * Limited functionality
  * Some memory and performance overhead associated with these structures


* NumPy provides multidimensional arrays (numpy.ndarray)
  * Can store many elements of the same data type in multiple dimensions
  * More functionality than core Python e.g. many conveninent methods for array manipulation
  * Efficient storage and execution

See, e.g.,
* http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.html


## Creating 1d arrays
Import `numpy` as <i>alias</i> "`np`"

In [47]:
import numpy as np

Many ways to create a 1d array e.g. from a list or a numpy array ("copy constructor")

In [48]:
a = np.array( [-1, 0, 1] )
b = np.array( a )
print(a)
print(b)

[-1  0  1]
[-1  0  1]


All NumPy arrays are of type '`ndarray`'

In [49]:
type(b)

numpy.ndarray

## Creating 1d arrays (cont.)
Can create arrays using `numpy` functions, e.g.

In [50]:
# arange for arrays (similar to range for lists)
a = np.arange( -2, 6, 2 )
print(a)

[-2  0  2  4]


In [51]:
# linspace to create sample step points in an interval
a = np.linspace(-10, 10, 5)
print(a)

[-10.  -5.   0.   5.  10.]


Can you guess what the following functions do?

In [52]:
b = np.zeros(3)
print(b)

[0. 0. 0.]


In [53]:
c = np.ones(3)
print(c)

[1. 1. 1.]


## Array attributes
As part of the array structure, NumPy keeps track of metadata for the array as "attributes"

In [54]:
# Taking "a" from the previous example
a = np.linspace(-10, 10, 5)

In [55]:
# Examine key array attributes
print(a)
print("Dimensions ", a.ndim)
print("Shape      ", a.shape)  # number of elements in each dim
print("Size       ", a.size)   # total number of elements
print("Data type  ", a.dtype)  # data type of element e.g. 32 bit float

[-10.  -5.   0.   5.  10.]
Dimensions  1
Shape       (5,)
Size        5
Data type   float64


Can specify data type at creation

In [56]:
a = np.array([1,2,3], np.float32)
print(a)
print("Data type", a.dtype)

[1. 2. 3.]
Data type float32


## Multi-dimensional arrays
Many different ways to create N-dimensional arrays. A two-dimensional array or matrix can be created from, e.g., list of lists

In [57]:
mat = np.array( [[1,2,3], [4,5,6]] )
print(mat)
print("Dimensions: ", mat.ndim)
print("Size:       ", mat.size)
print("Shape:      ", mat.shape)

[[1 2 3]
 [4 5 6]]
Dimensions:  2
Size:        6
Shape:       (2, 3)


Work out the shape of the resulting arrays before executing the following cells <br>
(HINT: length of the innermost list gives the size of the rightmost shape index)

In [58]:
i = np.array( [[1,1,1], [2,2,2], [3,3,3], [4,4,4]] )
print("i", i.shape)

i (4, 3)


In [59]:
j = np.array( [[[1,1],[2,2],[3,3],[4,4]],
               [[1,1],[2,2],[3,3],[4,4]],
               [[1,1],[2,2],[3,3],[4,4]]] )
print("j", j.shape)

j (3, 4, 2)


Can create 2d arrays with complex elements by specifying the data type

In [60]:
alist = [[1, 2, 3], [4, 5, 6]]
mat = np.array(alist, complex)
print(mat)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


## Accessing arrays
Basic indexing and slicing can be used to access array elements, as we know from lists

In [61]:
# a[start:stop:stride] (not inclusive of stop)
a = np.arange(8)
print("a", a)
print("a[0:7:2]", a[0:7:2])
print("a[0::2]", a[0::2])

a [0 1 2 3 4 5 6 7]
a[0:7:2] [0 2 4 6]
a[0::2] [0 2 4 6]


Negative indices are valid!

In [62]:
# Useful for accessing the last element
print(a[-3])

5


Can you guess the output of the following cells?

In [63]:
print(a[2:-3:2])

[2 4]


In [64]:
print(a[::-2])

[7 5 3 1]


## Accessing arrays (cont.)
For multi-dimensional arrays, can use a tuples or index notation.

In [65]:
# Basic indexing of a 3d array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.shape)
# using subscripts
print("c[1][0][1]:", c[1][0][1])
# using a tuple
print("c[(1,0,1)]:", c[1,0,1])
# the whole thing
print(c)

(2, 2, 2)
c[1][0][1]: 6
c[(1,0,1)]: 6
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


If the number of indices given is less than the number of axes, missing axes are taken as complete slices

In [66]:
print(c[1])
print(c[1,0,...]) # can also use elipsis (3 dots)
                  # for missing indices
print(c[1,0,1])

[[5 6]
 [7 8]]
[5 6]
6


## Array copies
Simple assignment creates references or 'shallow' copies of arrays

In [67]:
a = np.array( [-2,6,2] )
print("a", a)
b = a
a[0] = 20
print("b points to a!", b)

a [-2  6  2]
b points to a! [20  6  2]


Can query the "identity" of variables with function `id()`

In [68]:
print(id(a))
print(id(b)) # same as a

4414241744
4414241744


Use `copy()` to create a true or 'deep' copy

In [69]:
c = a.copy()
print(a)
print(id(c)) # not the same as a

[20  6  2]
4414571120


In [70]:
# check c really is an independent copy of a
c[0]=0
print("c changes", c)
print("a unaffected", a)

c changes [0 6 2]
a unaffected [20  6  2]


## Slices and views
A "view" is an array that refers to another array’s data (like references). You can create a view on an array by selecting a slice of an array. No data is copied when a view is created.

In [71]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [72]:
# Can assign a slice to a variable and change the
# array referred to by the slice
s = a[2:3, 1:3]
print(s)
s[:,:] = -2
print("s", s)
print("a", a)

[[8 9]]
s [[-2 -2]]
a [[ 1  2  3]
 [ 4  5  6]
 [ 7 -2 -2]]


Change all the elements with values 7,8,10,11 in matrix `m` below (i.e. bottom right corner elements) to 1000 using a slice

In [73]:
m = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(m)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## Reshaping arrays
Can modify the shape of an array and/or change its size.

In [74]:
a = np.arange(6)
print("a", a, ", shape:", a.shape)
# modifying the shape attribute (not a copy)
# requires that the size remains the same
a.shape = (3,2)
print(a)

a [0 1 2 3 4 5] , shape: (6,)
[[0 1]
 [2 3]
 [4 5]]


In [75]:
# Or can alter the size and shape of the array with
# resize(). May copy/pad depending on shape.
mat = np.arange(6)
print(mat)
mat1 = np.resize(mat, (3, 2))
print(mat1)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


Can check if arrays share the same data (i.e. not a copy) using `base`

In [76]:
mat1.base is mat # can also check this using id()

False

## Manipulating arrays
There are many methods for manipulating arrays (reshaping, joining, splitting, inserting, ...). Check the documentation.

E.g.,
```python
concatenate((a1,a2),axis=0)
split(a, indices_or_sections, axis=0)
flatten
ravel(a)
stack(arrays[, axis])
tile(a, reps)
repeat(a, repeats[, axis])
unique(ar[, return_index, return_inverse, ...])
trim_zeros(filt[, trim])
fill(scalar)
xv, yv = meshgrid(x,y)
```

 See what arrays you can create from some of the functions listed above.

## Fancy indexing
Advanced or fancy indexing lets you do more than simple indexing.


In [77]:
p = np.array([[0, 1, 2],[3, 4, 5],
              [6, 7, 8],[9, 10, 11]])
print(p)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [78]:
rows = [0,0,3,3]   # indices for rows
cols = [0,2,0,2]   # indices for columns
q=p[rows,cols]
print(q)

[ 0  2  9 11]


Fancy indexing returns a copy (not a view like slicing)

In [79]:
# ... check if a is a view or a copy
q[0]=1000
print(q)
print(p)

[1000    2    9   11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Use `base` or `id()` to check whether `q` is a copy. Do the same for a simple indexed slice of `p` (e.g. `p[1:2,3:4]`)

Can use logical expressions and boolean 'masks' to find indices of elements of interest e.g.

In [80]:
# Find indices of elements with value less than zero
m = np.array( [[0,-1,4,20,99],[-3,-5,6,7,-10]] )
print(m)
print(m[ m < 0 ])

[[  0  -1   4  20  99]
 [ -3  -5   6   7 -10]]
[ -1  -3  -5 -10]


Can you guess what the following code will output?

In [81]:
a = np.arange(10)
print(a)
mask = np.ones(len(a), dtype=bool)
mask[[0,2,4]] = False  # set values to False
result = a[mask]
print(result)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 6 7 8 9]


## Random number generation
NumPy provides utilities for random number generation

In [82]:
# Create an array of 10 random real numbers
a = np.random.ranf(10)
print(a)

[0.55712992 0.84087058 0.54631896 0.16998139 0.83508206 0.72257381
 0.30425069 0.20042193 0.19023723 0.31695618]


In [83]:
#ask for help
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [84]:
# Create a 2d array (5x5) reshaped matrix from a 1d array of (25)
# random ints between 0 and 5 (not inclusize)
a = np.random.randint(0, high=5, size=25).reshape(5,5)
print(a)

[[0 3 2 1 1]
 [2 3 3 1 4]
 [0 4 3 2 4]
 [1 2 1 4 4]
 [1 4 0 4 3]]


In [85]:
# Generate sample from normal distribution
# (default: mean=0, standard deviation=1)
s = np.random.standard_normal((2,2))
print(s)

[[-1.51642529 -0.90825843]
 [-0.41619807 -1.62749408]]


Explore other ways of generating random numbers.
What other distributions can you sample? Check exponential.

## File operations
NumPy provides an easy way to save data to text file

In [86]:
# Generate an array of 5 random real numbers
pts = 5
x = np.arange(pts)
y = np.random.random(pts)
print(x)
print(y)

[0 1 2 3 4]
[0.37994287 0.74209379 0.28266376 0.97610397 0.32742143]


In [87]:
print(np.stack((x,y),axis=1)) # stacking arrays along an axis

[[0.         0.37994287]
 [1.         0.74209379]
 [2.         0.28266376]
 [3.         0.97610397]
 [4.         0.32742143]]


In [88]:
# data format specifiers:
# d = int, f = float, e = exponential

'''
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)
%cd /content/drive/My Drive/Didattica/Corsi/AI/Lectures/Lecture1/


np.savetxt('data/savedata.txt', np.stack((x,y),axis=1), \
           header='DATA', \%pip install google

           footer='END', fmt='%d %1.4f')

'''
np.savetxt('./data/savedata.txt', np.stack((x,y),axis=1), \
           header='DATA',
           footer='END', fmt='%d %1.4f')

In [89]:
!cat data/savedata.txt

# DATA
0 0.3799
1 0.7421
2 0.2827
3 0.9761
4 0.3274
# END


In [90]:
# Reload data to an array
p = np.loadtxt('data/savedata.txt')
print(p)

[[0.     0.3799]
 [1.     0.7421]
 [2.     0.2827]
 [3.     0.9761]
 [4.     0.3274]]


More flexibility with `genfromtext()`  (query `?np.genfromtext`)

In [100]:
p = np.genfromtxt('data/savedata.txt', skip_header=1,
                  skip_footer=2)
print(p)

[[0.     0.3799]
 [1.     0.7421]
 [2.     0.2827]]


What do `numpy.save()` and `numpy.load()` do ?

## Performance
Python has a convenient timing function called `timeit`.

Can use this to measure the execution time of small code snippets.

* From python: `import timeit` and supply code  snippet as a string
* From ipython: can use magic command `%timeit`

By default, `%timeit` repeats the code 3 times and outputs the best time. It also tells you how many iterations it ran the code per repeat.
You can specify the number of repeats and the number of iterations per repeat.
```
%timeit -n <iterations> -r <repeats>  <code_snippet>
```

See

* `%timeit?` for more information
* https://docs.python.org/3/library/timeit.html


## Performance (cont.)
Here are some `timeit` experiments for you to try. Which methods are faster? (Note the kernel symbol is a filled circle when the kernel is busy.)


In [101]:
# Accessing a 2d array
nd = np.arange(100).reshape((10,10))

# accessing element of 2d array
%timeit -n 10000000 -r 3 nd[5][5]
%timeit -n 10000000 -r 3 nd[5,5]

98.1 ns ± 0.525 ns per loop (mean ± std. dev. of 3 runs, 10,000,000 loops each)
50.7 ns ± 0.164 ns per loop (mean ± std. dev. of 3 runs, 10,000,000 loops each)


#### Note
If you want to use a python script, have a look at the following example.

In [93]:
# Execute this cell to see a python script version
# of the above code
!cat solutions/example.py

cat: solutions/example.py: No such file or directory


## Exercise : Darts and calculating $\pi$
### A Monte Carlo method (aka "throwing darts")

Geometry gives us an expression for $\pi$: the area of a circle radius $r$ divided by the area of a square with length $r$:

$$
\pi = \pi r^2  / r^2
$$

We can estimate the area of a circle and a square by throwing darts. If $N_{in}$ is the number of darts falling on the dart board (quarter circle), and $N_{tot}$ is the total number of trials (i.e. darts falling on the square):

<img src="darts.png"; style="float: right; width: 25%; margin-right: 15%; margin-top: 0%; margin-bottom: 1%">  <br>

$$
\pi \approx 4 N_{in} / N_{tot}
$$

Try using numpy arrays to compute the following:
1. Choose a sample size `ntot`
2. Generate an array of random $x$ coordinates $0 \leq x < 1$.
3. Generate an array of random $y$ coordinates $0 \leq y < 1$.
4. Count the number for which $x^2 + y^2 < 1$
5. Compute appromination to $\pi$

<br>

In [94]:
# Try a solution here, or write a script ...

In [95]:
# Execute this cell to see a solution
!cat solutions/darts.py

cat: solutions/darts.py: No such file or directory


In [96]:
# or execute this cell to run the script
%run solutions/darts.py

Exception: File `'solutions/darts.py'` not found.

# Summary
---

* Numpy introduces multi-dimensional arrays to Python
* It also provides fast numerical routines convenient for scientific computation
